UNITS = {
    'Heavy Cavalry': {'count': 4},
    'Light Cavalry': {'count': 5},
    'Archer': {'count': 4},
    'Crossbowman': {'count': 5},
    'Footman': {'count': 5},
    'Swordsman': {'count': 5},
    'Knight': {'count': 4},
    'Mercenary': {'count': 5},
    'Ensign': {'count': 5},
    'Marshall': {'count': 5},
    'Berserker': {'count': 5},
    'Royal Guard': {'count': 5},
    'Scout': {'count': 5},
    'Lancer': {'count': 4},
    'Pikeman': {'count': 4},
    'Warrior Priest': {'count': 4},
}
